# Generated by Django 5.0.1 on 2024-02-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_fertilise_plants_period_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='todolist',
            new_name='list',
        ),
    ]
