# Generated by Django 5.0.1 on 2024-02-08 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_list_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ToDoList',
        ),
    ]
