# Generated by Django 5.0.1 on 2024-02-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_list_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
