# Generated by Django 5.0.1 on 2024-02-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_todolist_user_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='fertilise',
            new_name='period',
        ),
    ]
