# Generated by Django 5.0.1 on 2024-02-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_fertilise_plants_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantlist',
            name='plantAmount',
            field=models.IntegerField(default=0),
        ),
    ]
